---
- name: Criar usuário no PostgreSQL com acesso a banco via Survey (AAP)
  hosts: db_servers
  become: true
  vars:
    db_username: "{{ username }}"
    db_user_password: "{{ user_password }}"
    db_name: "{{ target_database }}"
    db_privileges: "{{ privileges }}"

  tasks:
    - name: Criar usuário com senha (se não existir)
      become_user: postgres
      shell: |
        psql -tc "SELECT 1 FROM pg_roles WHERE rolname='{{ db_username }}';" | grep -q 1 || \
        psql -c "CREATE ROLE {{ db_username }} WITH LOGIN PASSWORD '{{ db_user_password }}';"
      register: create_user_output
      changed_when: "'CREATE ROLE' in create_user_output.stdout"

    - name: Conceder privilégios no banco de dados
      become_user: postgres
      shell: |
        psql -d {{ db_name }} -c "GRANT {{ db_privileges }} ON DATABASE {{ db_name }} TO {{ db_username }};"
      register: grant_output
      changed_when: "'GRANT' in grant_output.stdout"

    - name: Confirmar criação e acesso
      debug:
        msg: "Usuário '{{ db_username }}' criado e recebeu '{{ db_privileges }}' no banco '{{ db_name }}'"
