---
- name: Atualizar refresh interval de um dashboard no Grafana
  hosts: localhost
  gather_facts: no
  vars:
    grafana_url: "http://192.168.100.1:3000"
    grafana_user: "admin"
    grafana_password: "sua_senha"
    dashboard_uid: "a2848c19-ddf5-47c5-b2e6-6e5c6966cda7"
    new_refresh: "30s"

  tasks:
    - name: Buscar dashboard atual
      uri:
        url: "{{ grafana_url }}/api/dashboards/uid/{{ dashboard_uid }}"
        method: GET
        user: "{{ grafana_user }}"
        password: "{{ grafana_password }}"
        force_basic_auth: yes
        return_content: yes
        validate_certs: no
        status_code: 200
      register: dashboard_data

    - name: Atualizar refresh interval do dashboard
      uri:
        url: "{{ grafana_url }}/api/dashboards/db"
        method: POST
        user: "{{ grafana_user }}"
        password: "{{ grafana_password }}"
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
        body_format: json
        body: |
          {
            "dashboard": {{ dashboard_data.json.dashboard | combine({'refresh': new_refresh}) }},
            "overwrite": true
          }
        validate_certs: no
        status_code: 200
      register: update_result

    - name: Mostrar resposta da atualização
      debug:
        var: update_result.json

