---
- name: Health check PostgreSQL (pré-automação)
  hosts: db_servers
  become: true
  vars:
    db: "postgres"
  tasks:
    - name: Serviço e versão
      shell: |
        systemctl is-enabled postgresql; systemctl is-active postgresql; postgres -V
      register: svc
      changed_when: false
    - debug: var=svc.stdout_lines

    - name: Conexões
      become_user: postgres
      command: psql -tAc "SELECT count(*) total, (SELECT setting::int FROM pg_settings WHERE name='max_connections') max FROM pg_stat_activity;"
      register: conns
      changed_when: false
    - debug: var=conns.stdout

    - name: Portas
      shell: ss -ltnp | grep 5432 || true
      register: ports
      changed_when: false
    - debug: var=ports.stdout

    - name: Bancos e roles
      become_user: postgres
      command: psql -tAc "SELECT datname FROM pg_database WHERE datistemplate=false;"
      register: dbs
      changed_when: false
    - debug: var=dbs.stdout_lines

    - name: Erros recentes (últimas 100 linhas do último log)
      shell: |
        LOGDIR=$(sudo -u postgres psql -tAc "SHOW log_directory;")
        LAST=$(ls -1t /var/lib/pgsql/data/${LOGDIR} | head -1)
        tail -n 100 /var/lib/pgsql/data/${LOGDIR}/${LAST} | egrep -i "ERROR|FATAL|PANIC" || true
      register: errs
      changed_when: false
    - debug: var=errs.stdout

