---
- name: Instalação e configuração do PostgreSQL Server
  hosts: server01.aroque.com.br
  become: true

  vars:
    pg_data_dir: "/var/lib/pgsql/data"

  tasks:
    - name: Instalar pacote postgresql-server
      ansible.builtin.package:
        name: postgresql-server
        state: present

    - name: Verificar se o cluster já foi inicializado
      ansible.builtin.stat:
        path: "{{ pg_data_dir }}/PG_VERSION"
      register: pgver

    - name: Inicializar cluster (equivale a postgresql-setup --initdb)
      ansible.builtin.command: postgresql-setup --initdb
      when: not pgver.stat.exists

    - name: Iniciar e habilitar serviço postgresql
      ansible.builtin.service:
        name: postgresql
        state: started
        enabled: true

    - name: Exibir versão do PostgreSQL
      become_user: postgres
      ansible.builtin.command: psql -tAc "SELECT version();"
      register: pg_ver
      changed_when: false

    - name: Mostrar versão retornada
      ansible.builtin.debug:
        var: pg_ver.stdout
