- name: Automate SNOW - Change Request Close
  hosts: localhost
  connection: local
  collections:
    - servicenow.itsm
  vars:
    snow_instance: "{{ snow_instance }}"
    snow_username: "{{ snow_username }}"
    snow_password: "{{ snow_password }}"

    sn_change_number: "{{ sn_change_number }}"
    sn_close_code:   "{{ sn_close_code | default('successful') }}"
    sn_close_notes:  "{{ sn_close_notes | default('Closed by Ansible') }}"

  tasks:
    - name: Close change request
      servicenow.itsm.change_request:
        instance:
          host: "{{ snow_instance }}"
          username: "{{ snow_username }}"
          password: "{{ snow_password }}"
        number: "{{ sn_change_number }}"
        state: closed
        close_code: "{{ sn_close_code }}"
        close_notes: "{{ sn_close_notes }}"
        other:
          work_notes: "{{ sn_close_notes }}"
      register: closed_change
