---
- name: Criar usuário no PostgreSQL (sem verificação)
  hosts: db_servers
  become: true
  vars:
    db_command:

  tasks:
    - name: Criar usuário no PostgreSQL com senha
      become_user: postgres
      ansible.builtin.shell: |
        {{ db_command }}
      register: create_user_output
      changed_when: "'CREATE ROLE' in create_user_output.stdout"
      ignore_errors: yes
