---
collections:
  - name: servicenow.itsm
    version: ">=1.0.0"
  - name: community.postgresql
    version: ">=2.0.0"
  - name: ansible.posix
    version: ">=1.4.0"
  - name: ansible.utils
    version: ">=2.0.0"
